export const CROSSING_MEDIA = {
  journey: '/encre-de-sel/traversee/passage.webp',
  journeyMobile: '/encre-de-sel/traversee/passage-mobile.webp',
  narrative: '/encre-de-sel/landing/partie.webp',
  inn: '/encre-de-sel/landing/auberge.webp',
} as const

export const CROSSING_COPY = {
  fr: {
    skip: 'Aller au contenu',
    game: 'Le jeu',
    world: 'L’univers',
    login: 'Connexion',
    playShort: 'Jouer',
    resumeShort: 'Reprendre',
    play: 'Jouer maintenant',
    resume: 'Reprendre ma chronique',
    title: ['Tente l’impossible.', 'Assume la suite.'],
    intro: 'Un roguelike narratif solo. Tes mots ouvrent la voie. Les règles décident.',
    discover: 'Découvrir le jeu',
    meta: 'Dans le navigateur · Solo · FR / EN',
    passage: ['Un passage.', 'Mille façons d’oser.'],
    situation: 'Un garde bloque la route. À toi d’écrire la suite.',
    proof: 'Des mots. Des règles. Des conséquences.',
    proofBody:
      'Tu proposes une action. Le jeu en arbitre l’issue. Le récit porte les traces de tes décisions.',
    previewLabel: 'Aperçu narratif scénarisé',
    previewTitle: 'Le monde te répond.',
    previewBody:
      'Une chaîne barre le chemin. Sous sa capuche, le garde attend. Tu peux lui parler, observer les alentours… ou tenter autre chose.',
    continue: 'Commencer mon histoire',
    innLabel: 'Retour à l’Auberge',
    innTitle: 'L’Aveugle t’attend.',
    innBody: 'Donne un nom à ton prochain survivant. Ta prochaine histoire commence ici.',
    enter: 'Entrer dans l’Auberge',
    chronicle: 'Ma chronique',
    created: 'Créé par Adem',
    pause: 'Mettre les animations en pause',
    unpause: 'Reprendre les animations',
  },
  en: {
    skip: 'Skip to content',
    game: 'The game',
    world: 'The world',
    login: 'Sign in',
    playShort: 'Play',
    resumeShort: 'Resume',
    play: 'Play now',
    resume: 'Resume my chronicle',
    title: ['Attempt the impossible.', 'Live with what follows.'],
    intro: 'A solo narrative roguelike. Your words open the way. The rules decide.',
    discover: 'Discover the game',
    meta: 'In your browser · Solo · FR / EN',
    passage: ['One passage.', 'A thousand ways to dare.'],
    situation: 'A guard blocks the road. Write what happens next.',
    proof: 'Words. Rules. Consequences.',
    proofBody:
      'You propose an action. The game resolves its outcome. The story carries the traces of your decisions.',
    previewLabel: 'Scripted narrative preview',
    previewTitle: 'The world answers.',
    previewBody:
      'A chain blocks the path. Beneath his hood, the guard waits. Talk to him, look around… or try something else.',
    continue: 'Begin my story',
    innLabel: 'Back to the Inn',
    innTitle: 'The Blind One awaits.',
    innBody: 'Name your next survivor. Your next story starts here.',
    enter: 'Enter the Inn',
    chronicle: 'My chronicle',
    created: 'Created by Adem',
    pause: 'Pause animations',
    unpause: 'Resume animations',
  },
} as const

export type CrossingCopy = (typeof CROSSING_COPY)[keyof typeof CROSSING_COPY]
